name: build and deploy spring-spell-checker
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: build and deploy spring-spell-checker
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: unit tests
        run: mvn -B test --file pom.xml

      - name: build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: DockerfileSpring
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-spell-checker:v1.0.0

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: DockerfileSpring
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-spell-checker:v1.0.0
